{% set name = "pycdlib" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycdlib-{{ version }}.tar.gz
  sha256: 6889dc7fdb8afd2b464f4471df7781178d092473d92e9d9aeb14a0bc7db0bace

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - pycdlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/clalancette/pycdlib
  summary: Pure python ISO manipulation library
  license: LGPL-2.1-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - ajaypnair09
