{% set name = "pycdlib" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycdlib-{{ version }}.tar.gz
  sha256: da02ce3d3a7cc1f879cd84db7bb39427a082cee0dbf0730fec89604039344058

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - pycdlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/clalancette/pycdlib
  summary: Pure python ISO manipulation library
  license: LGPL-2.1-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - ajaypnair09
