{% set name = "pycdlib" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycdlib-{{ version }}.tar.gz
  sha256: 8ec306b31d9c850f28c5fda52438d904edd1e8fcf862c5ffd756272efac9f422

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pycdlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/clalancette/pycdlib
  summary: Pure python ISO manipulation library
  license: LGPL-2.1-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - ajaypnair09
